# DStudio — native desktop app for ds4 (server + agent + design).
#
#   make            macOS: builds DStudio.app (double-click, no Terminal)
#                   Linux: builds ./dstudio (the same app, WebKitGTK window)
#   make run        compiles and starts (opens the window on the interface)
#   make check      sanity: the page is valid text and the pure modules pass the tests
#   make windows    Windows portable zip (run from Windows with PowerShell + toolchains)
#   make clean      removes the binary and the generated artifacts
#
# Architecture: dstudio.c is the HTTP server (compiled with -DDS4_WITH_WEBVIEW, its
# main becomes ds4_serve_main); app.cc is the entry point that forks the server
# and opens the native webview window (WKWebView on macOS, WebKitGTK on Linux,
# via webview.h). index.html is embedded in the binary in base64 (page_data.h);
# the logo is embedded too (logo_data.h) for the Linux window icon.

CC      ?= cc
WARN_CFLAGS ?= -Wall -Wextra
WARN_CXXFLAGS ?= -Wall
ifeq ($(STRICT_WARNINGS),1)
  WARN_CFLAGS += -Wpedantic -Werror
  WARN_CXXFLAGS += -Wextra -Wpedantic -Werror
endif
CFLAGS  ?= -O2 $(WARN_CFLAGS) -std=c11
PORT    ?= 5500
DS4_DIR ?= ../ds4

BIN      := dstudio
SRC      := src/dstudio.c
APP      := src/app.cc
HDR      := src/webview.h
PAGE     := web/index.html
GEN      := src/page_data.h
LOGO     := assets/logo.png
LOGO_HDR := src/logo_data.h
ICNS     := ds4.icns
PLIST    := assets/Info.plist

# Webview backend per platform.
UNAME := $(shell uname)
ifeq ($(UNAME),Darwin)
  APPCXX       := clang++
  APP_CXXFLAGS := -x objective-c++ -fno-objc-arc -std=c++11 -O2 $(WARN_CXXFLAGS)
  APP_LDFLAGS  := -framework Cocoa -framework WebKit \
                  -Wl,-sectcreate,__TEXT,__info_plist,$(PLIST)
  APP_DEPS     := $(HDR)                 # macOS icon comes from the .icns
  BIN_DEPS     := $(ICNS) $(PLIST)       # .icns built by sips/iconutil (macOS-only)
else
  APPCXX       := $(CXX)
  APP_CXXFLAGS := -x c++ -std=c++11 -O2 $(WARN_CXXFLAGS) $(shell pkg-config --cflags gtk+-3.0 webkit2gtk-4.1)
  APP_LDFLAGS  := $(shell pkg-config --libs gtk+-3.0 webkit2gtk-4.1)
  APP_DEPS     := $(HDR) $(LOGO_HDR)     # Linux icon comes from the embedded logo
  BIN_DEPS     :=                        # no .icns on Linux (logo is baked into app.o)
endif

.PHONY: all run check clean app windows

# One `make` gives the right artifact per platform, both branded with the same
# logo: the double-clickable bundle on macOS, the windowed binary on Linux.
ifeq ($(UNAME),Darwin)
all: app
else
all: $(BIN)
endif

# macOS bundle: DStudio.app launches with a double click from the Finder, WITHOUT a Terminal.
# The binary in the bundle is copied with -X (no resource fork: codesign rejects
# the "detritus"); the bundle icon comes from the .icns in Resources.
APPNAME := DStudio
APPDIR  := $(APPNAME).app
app: $(BIN)
ifeq ($(UNAME),Darwin)
	@rm -rf $(APPDIR)
	@mkdir -p $(APPDIR)/Contents/MacOS $(APPDIR)/Contents/Resources
	@cp -X $(BIN) $(APPDIR)/Contents/MacOS/$(APPNAME)
	@cp $(ICNS) $(APPDIR)/Contents/Resources/ds4.icns
	@cp $(PLIST) $(APPDIR)/Contents/Info.plist
	@/usr/libexec/PlistBuddy -c 'Add :CFBundleExecutable string $(APPNAME)' $(APPDIR)/Contents/Info.plist >/dev/null 2>&1 || true
	@/usr/libexec/PlistBuddy -c 'Add :CFBundleIconFile string ds4' $(APPDIR)/Contents/Info.plist >/dev/null 2>&1 || true
	@/usr/libexec/PlistBuddy -c 'Add :CFBundleShortVersionString string 1.0' $(APPDIR)/Contents/Info.plist >/dev/null 2>&1 || true
	@/usr/libexec/PlistBuddy -c 'Add :CFBundleVersion string 1' $(APPDIR)/Contents/Info.plist >/dev/null 2>&1 || true
	@codesign --force -s - $(APPDIR) >/dev/null 2>&1 && echo "$(APPDIR): ad-hoc signature ok" || echo "$(APPDIR): signature skipped"
	@echo "$(APPDIR) ready: double click to start (no Terminal)."
else
	@echo "make app is for macOS only"
endif

# Binary icon: logo.png resized into a multi-resolution .icns.
# Applied to the binary resource fork (xattr), NOT to the data fork → the linker
# ad-hoc signature stays valid and the binary runs on arm64.
$(ICNS): $(LOGO)
	@rm -rf ds4.iconset && mkdir -p ds4.iconset
	@for s in 16 32 128 256 512; do \
	  sips -z $$s $$s $(LOGO) --out ds4.iconset/icon_$${s}x$${s}.png >/dev/null 2>&1; \
	  d=$$((s*2)); sips -z $$d $$d $(LOGO) --out ds4.iconset/icon_$${s}x$${s}@2x.png >/dev/null 2>&1; \
	done
	@iconutil -c icns ds4.iconset -o $(ICNS) && rm -rf ds4.iconset
	@echo "$(ICNS): icon generated from $(LOGO) (resized)"

# Embeds index.html in the binary in base64 (generated header).
# tr -d '\n' → pure base64 stream; od/awk emits a numeric char array instead
# of one huge string literal, so strict GCC/Clang builds stay warning-free.
$(GEN): $(PAGE)
	@{ \
	  echo '/* GENERATED by Makefile — do not edit. base64 of index.html */'; \
	  echo 'static const char PAGE_B64[] = {'; \
	  base64 < $(PAGE) | tr -d '\n' | od -An -v -tu1 | awk '{ for (i = 1; i <= NF; i++) printf "%s,", $$i }'; \
	  echo '0};'; \
	} > $(GEN)
	@echo "$(GEN): $$(wc -c < $(GEN) | tr -d ' ') bytes"

# Embeds assets/logo.png in the binary as raw bytes (generated header), used as
# the GTK window icon on Linux — no asset file at runtime. macOS ignores it (it
# gets its icon from the .icns), so this is only a prerequisite of the Linux build.
$(LOGO_HDR): $(LOGO)
	@{ \
	  echo '/* GENERATED by Makefile — do not edit. bytes of assets/logo.png */'; \
	  echo 'static const unsigned char LOGO_PNG[] = {'; \
	  od -An -v -tu1 < $(LOGO) | awk '{ for (i = 1; i <= NF; i++) printf "%s,", $$i }'; \
	  echo ''; \
	  echo '};'; \
	  echo 'static const unsigned int LOGO_PNG_LEN = sizeof(LOGO_PNG);'; \
	} > $(LOGO_HDR)
	@echo "$(LOGO_HDR): embedded $$(wc -c < $(LOGO) | tr -d ' ') bytes of $(LOGO)"

# HTTP server (dstudio.c) as an object: its main becomes ds4_serve_main.
dstudio.o: $(SRC) $(GEN)
	$(CC) $(CFLAGS) -DDS4_WITH_WEBVIEW -c $(SRC) -o dstudio.o

# Entry point + native webview window. On Linux $(APP_DEPS) pulls in logo_data.h.
app.o: $(APP) $(APP_DEPS)
	$(APPCXX) $(APP_CXXFLAGS) -c $(APP) -o app.o

$(BIN): dstudio.o app.o $(BIN_DEPS)
	$(APPCXX) dstudio.o app.o $(APP_LDFLAGS) -o $@
ifeq ($(UNAME),Darwin)
	@# custom icon in the resource fork; does not touch data fork or signature (see above)
	@cp $(ICNS) .icontmp.icns 2>/dev/null && sips -i .icontmp.icns >/dev/null 2>&1 \
	  && DeRez -only icns .icontmp.icns > .icontmp.rsrc 2>/dev/null \
	  && Rez -append .icontmp.rsrc -o $@ 2>/dev/null \
	  && SetFile -a C $@ 2>/dev/null \
	  && echo "icon applied to $@" \
	  || echo "icon not applied (macOS tools missing?)"; \
	  rm -f .icontmp.icns .icontmp.rsrc
endif

run: $(BIN)
	./$(BIN) $(PORT) $(DS4_DIR)

# Lightweight check without dependencies: the page must stay text (not binary)
# and, if node is present, the pure modules (sse/holdback/markdown) must pass the tests.
check: $(BIN)
	@file $(PAGE) | grep -q text && echo "$(PAGE): text OK" || (echo "$(PAGE) is not text!" && exit 1)
	@command -v node >/dev/null 2>&1 && { \
	  awk '/<script type="module">/{f=1;next} /<\/script>/{f=0} f' $(PAGE) > /tmp/ds4ui-js.mjs; \
	  node --check /tmp/ds4ui-js.mjs && echo "JS: syntax OK"; \
	} || echo "node missing: skipping the JS check"

windows:
	pwsh -NoProfile -ExecutionPolicy Bypass -File scripts/build-windows.ps1

clean:
	rm -f $(BIN) $(GEN) $(LOGO_HDR) $(ICNS) dstudio.o app.o
	@rm -rf ds4.iconset .icontmp.icns .icontmp.rsrc
