#!/bin/sh

out=
src=
target=
defs=

while [ "$#" -gt 0 ]; do
    case "$1" in
    -O) ;;
    -D*) defs="$defs $1" ;;
    --target-env=*) target=${1#*=} ;;
    -o)
        shift
        out=$1
        ;;
    *) src=$1 ;;
    esac
    shift
done

set -- -V -Os -S comp
if [ -n "$target" ]; then
    set -- "$@" --target-env "$target"
fi
exec glslangValidator "$@" $defs -o "$out" "$src"
