param(
  [string]$Ds4Dir = "",
  [string]$CygwinRoot = "",
  [string]$OutDir = "dist\DStudio-windows-x64"
)

$ErrorActionPreference = "Stop"
$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Set-Location $Root

function Assert-NativeOk([string]$Name) {
  if ($LASTEXITCODE -ne 0) {
    throw "$Name failed with exit code $LASTEXITCODE"
  }
}

function Get-NativeTool([string[]]$Names) {
  foreach ($Name in $Names) {
    $Tool = Get-Command $Name -ErrorAction SilentlyContinue
    if ($Tool) { return $Tool.Source }
  }
  throw "none of these tools were found in PATH: $($Names -join ', ')"
}

function Write-Base64Header([string]$InputPath, [string]$OutputPath, [string]$Symbol, [string]$Label) {
  $bytes = [IO.File]::ReadAllBytes($InputPath)
  $b64 = [Convert]::ToBase64String($bytes)
  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("/* GENERATED by scripts/build-windows.ps1 - do not edit. base64 of $Label */")
  $lines.Add("static const char $Symbol[] = {")
  $b64Bytes = [Text.Encoding]::ASCII.GetBytes($b64)
  for ($i = 0; $i -lt $b64Bytes.Length; $i += 32) {
    $take = [Math]::Min(32, $b64Bytes.Length - $i)
    $chunk = $b64Bytes[$i..($i + $take - 1)]
    $lines.Add("  " + (($chunk | ForEach-Object { [string]$_ }) -join ",") + ",")
  }
  $lines.Add("  0")
  $lines.Add("};")
  [IO.File]::WriteAllLines($OutputPath, $lines)
}

function Write-IcoFromPng([string]$PngPath, [string]$IcoPath) {
  Add-Type -AssemblyName System.Drawing
  $src = [Drawing.Image]::FromFile($PngPath)
  try {
    $bmp = New-Object Drawing.Bitmap 256, 256
    try {
      $g = [Drawing.Graphics]::FromImage($bmp)
      try {
        $g.Clear([Drawing.Color]::Transparent)
        $g.InterpolationMode = [Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $g.SmoothingMode = [Drawing.Drawing2D.SmoothingMode]::HighQuality
        $g.PixelOffsetMode = [Drawing.Drawing2D.PixelOffsetMode]::HighQuality
        $g.DrawImage($src, 0, 0, 256, 256)
      } finally {
        $g.Dispose()
      }
      $png = New-Object IO.MemoryStream
      try {
        $bmp.Save($png, [Drawing.Imaging.ImageFormat]::Png)
        $bytes = $png.ToArray()
      } finally {
        $png.Dispose()
      }
    } finally {
      $bmp.Dispose()
    }
  } finally {
    $src.Dispose()
  }

  $fs = [IO.File]::Open($IcoPath, [IO.FileMode]::Create, [IO.FileAccess]::Write)
  $bw = New-Object IO.BinaryWriter($fs)
  try {
    $bw.Write([UInt16]0)       # reserved
    $bw.Write([UInt16]1)       # image type: icon
    $bw.Write([UInt16]1)       # image count
    $bw.Write([Byte]0)         # 256 px
    $bw.Write([Byte]0)         # 256 px
    $bw.Write([Byte]0)         # palette
    $bw.Write([Byte]0)         # reserved
    $bw.Write([UInt16]1)       # color planes
    $bw.Write([UInt16]32)      # bits per pixel
    $bw.Write([UInt32]$bytes.Length)
    $bw.Write([UInt32]22)      # ICO header + directory entry
    $bw.Write($bytes)
  } finally {
    $bw.Dispose()
    $fs.Dispose()
  }
}

if (-not $Ds4Dir) {
  $Candidates = @(
    (Join-Path (Split-Path $Root -Parent) "ds4"),
    (Join-Path (Split-Path (Split-Path $Root -Parent) -Parent) "ds4")
  )
  $Ds4Dir = $Candidates | Where-Object { Test-Path (Join-Path $_ "Makefile") } | Select-Object -First 1
  if (-not $Ds4Dir) {
    $Ds4Dir = $Candidates[0]
  }
}
$Ds4Dir = (Resolve-Path $Ds4Dir).Path

New-Item -ItemType Directory -Force -Path "src" | Out-Null
New-Item -ItemType Directory -Force -Path "build\windows" | Out-Null
if (Test-Path $OutDir) { Remove-Item $OutDir -Recurse -Force }
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

Write-Host "windows: generating embedded page headers"
Write-Base64Header `
  (Join-Path $Root "web\index.html") `
  (Join-Path $Root "src\page_data.h") `
  "PAGE_B64" `
  "index.html"
Write-Base64Header `
  (Join-Path $Root "web\loading.html") `
  (Join-Path $Root "src\loading_data.h") `
  "LOADING_B64" `
  "loading.html"

Write-Host "windows: generating app icon resource"
$Icon = Join-Path $Root "build\windows\dstudio.ico"
$Rc = Join-Path $Root "build\windows\dstudio.rc"
$Res = Join-Path $Root "build\windows\dstudio.res"
Write-IcoFromPng (Join-Path $Root "assets\logo.png") $Icon
[IO.File]::WriteAllText($Rc, "101 ICON `"$Icon`"`r`n")
rc /nologo /fo $Res $Rc
Assert-NativeOk "compile Windows icon resource"

Write-Host "windows: restoring WebView2 SDK"
$Deps = Join-Path $Root ".deps\windows"
New-Item -ItemType Directory -Force -Path $Deps | Out-Null
nuget install Microsoft.Web.WebView2 -Version 1.0.2903.40 -OutputDirectory $Deps -NonInteractive
Assert-NativeOk "nuget install WebView2"
$Pkg = Get-ChildItem $Deps -Directory -Filter "Microsoft.Web.WebView2.*" | Sort-Object Name -Descending | Select-Object -First 1
if (-not $Pkg) { throw "WebView2 SDK not found after nuget install" }
$WvInclude = Join-Path $Pkg.FullName "build\native\include"
$StaticLib = Get-ChildItem $Pkg.FullName -Recurse -Filter "WebView2LoaderStatic.lib" |
  Where-Object { $_.FullName -match "\\x64\\" } | Select-Object -First 1
$DynamicLib = Get-ChildItem $Pkg.FullName -Recurse -Filter "WebView2Loader.dll.lib" |
  Where-Object { $_.FullName -match "\\x64\\" } | Select-Object -First 1
$LinkLib = if ($DynamicLib) { $DynamicLib.FullName } elseif ($StaticLib) { $StaticLib.FullName } else { throw "WebView2 loader lib not found" }

Write-Host "windows: compiling DStudio.exe"
$Cl = Get-NativeTool @("clang-cl", "cl")
& $Cl /nologo /O2 /W3 /D_CRT_SECURE_NO_WARNINGS /D_WINSOCK_DEPRECATED_NO_WARNINGS /DDS4_WITH_WEBVIEW /TC /c src\dstudio.c /Fobuild\windows\dstudio.obj
Assert-NativeOk "compile dstudio.c"
& $Cl /nologo /O2 /W3 /EHsc /std:c++17 /D_CRT_SECURE_NO_WARNINGS /I "$WvInclude" /c src\app.cc /Fobuild\windows\app.obj
Assert-NativeOk "compile app.cc"
& $Cl /nologo build\windows\dstudio.obj build\windows\app.obj $Res /Fe:$OutDir\DStudio.exe /link /SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup ws2_32.lib user32.lib shell32.lib ole32.lib uuid.lib version.lib $LinkLib
Assert-NativeOk "link DStudio.exe"

if ($DynamicLib) {
  $Dll = Get-ChildItem $Pkg.FullName -Recurse -Filter "WebView2Loader.dll" |
    Where-Object { $_.FullName -match "\\win-x64\\" -or $_.FullName -match "\\x64\\" } | Select-Object -First 1
  if ($Dll) { Copy-Item $Dll.FullName $OutDir -Force }
}

Write-Host "windows: building DS4 CPU staging via POSIX toolchain"
if (-not $CygwinRoot) {
  if (Test-Path "C:\msys64\usr\bin\bash.exe") { $CygwinRoot = "C:\msys64\usr" }
  elseif (Test-Path "C:\cygwin64\bin\bash.exe") { $CygwinRoot = "C:\cygwin64" }
  else { throw "No MSYS2/Cygwin bash found" }
}
$Bash = Join-Path $CygwinRoot "bin\bash.exe"
if (-not (Test-Path $Bash)) { throw "POSIX bash not found: $Bash" }
& $Bash -lc "true"
Assert-NativeOk "initialize POSIX shell"
if ($CygwinRoot -like "*msys64*") {
  & $Bash -lc "export PATH=/usr/local/bin:/usr/bin:/bin:`$PATH; pacman --noconfirm -S --needed make patch gcc"
  Assert-NativeOk "install MSYS2 build tools"
}
$RootUnix = ((& $Bash -lc "cygpath -u '$Root'") | Select-Object -Last 1).Trim()
Assert-NativeOk "cygpath root"
$Ds4Unix = ((& $Bash -lc "cygpath -u '$Ds4Dir'") | Select-Object -Last 1).Trim()
Assert-NativeOk "cygpath ds4"
& $Bash -lc "cd '$RootUnix' && ./scripts/build-ds4-windows-cygwin.sh '$Ds4Unix'"
Assert-NativeOk "build DS4 Windows engine"

Write-Host "windows: copying engine binaries and runtime"
$Engine = @("ds4-server.exe", "ds4-agent-jsonl.exe", "ds4-design.exe")
foreach ($e in $Engine) {
  $src = Join-Path $Ds4Dir $e
  if (-not (Test-Path $src)) { throw "missing engine binary: $src" }
  Copy-Item $src $OutDir -Force
}
$JsonlVer = Join-Path $Ds4Dir "ds4-agent-jsonl.ver"
if (-not (Test-Path $JsonlVer)) { throw "missing JSONL runtime version marker: $JsonlVer" }
Copy-Item $JsonlVer $OutDir -Force

$RuntimeDlls = @(
  "libgcc_s_seh-1.dll", "libwinpthread-1.dll", "libstdc++-6.dll"
)
foreach ($dll in $RuntimeDlls) {
  $src = $null
  foreach ($dir in @(
    "C:\msys64\ucrt64\bin",
    "C:\msys64\mingw64\bin",
    "C:\msys64\clang64\bin"
  )) {
    $candidate = Join-Path $dir $dll
    if (Test-Path $candidate) { $src = $candidate; break }
  }
  if ($src) {
    Copy-Item $src $OutDir -Force
  }
}

@"
DStudio Windows x64 portable

Run DStudio.exe. The DS4 engine binaries in this folder are CPU-only Windows
builds produced from a temporary staging copy; the upstream ds4 checkout is not
modified permanently.

Agent and Design LAN-client mode use the local DS4 tools for workspace actions
and DStudio's internal model bridge for LAN inference. Do not copy MSYS/Cygwin
runtime DLLs next to the DS4 binaries: the launcher adds the installed MSYS2
runtime to PATH so /tmp, fork and shell tools keep the correct MSYS root.

Models are not included. Put GGUF files in the selected ds4 folder, or point
DStudio at a ds4 folder that already contains them.
"@ | Set-Content -Encoding UTF8 (Join-Path $OutDir "README-WINDOWS.md")

$Zip = "dist\DStudio-windows-x64.zip"
if (Test-Path $Zip) { Remove-Item $Zip -Force }
Compress-Archive -Path (Join-Path $OutDir "*") -DestinationPath $Zip
Write-Host "windows: artifact ready: $Zip"
